stages:
  - test
  - build
  - deploy

## Test
op-api-unit-test-job:
    image: python:3-bullseye
    stage: test
    script:
        - cd op_api
        - pip install -r requirements.txt
        - python -m pytest

## BUILD
build-front-end-job:
  stage: build
  image: node:lts-bullseye
  variables:
    REACT_APP_API_HOST: https://onlypicks.herokuapp.com 
    PUBLIC_URL: https://team-7-mission.gitlab.io/only-picks/
  script:
    - cd ghi
    - npm install
    - npm run build
    - cp build/index.html build/404.html
  artifacts:
    paths:
      - ghi/build/

build-only-picks-api-image-job:  # RENAMED
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  script:
    - cd op_api
    - docker build -t ${CI_REGISTRY_IMAGE}/op_api:latest .
    - docker tag ${CI_REGISTRY_IMAGE}/op_api:latest ${CI_REGISTRY_IMAGE}/op_api:$CI_JOB_ID
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push ${CI_REGISTRY_IMAGE}/op_api:$CI_JOB_ID
    - docker push ${CI_REGISTRY_IMAGE}/op_api:latest

deploy-only-picks-api-image-job:  # RENAMED
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  stage: deploy
  image: docker:20.10.16
  needs:
    - build-only-picks-api-image-job
  services:
    - docker:20.10.16-dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
    - docker pull ${CI_REGISTRY_IMAGE}/op_api:latest
    - docker tag ${CI_REGISTRY_IMAGE}/op_api:latest registry.heroku.com/$HEROKU_FASTAPI_APP/web:latest
    - docker push registry.heroku.com/$HEROKU_FASTAPI_APP/web:latest

release-only-picks-api-image-job:  # RENAMED 
  stage: deploy
  image: node:10.17-alpine
  needs:
    - deploy-only-picks-api-image-job
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  before_script:
    - apk add curl bash
    - curl https://cli-assets.heroku.com/install.sh | sh
  script:
    - heroku container:release web --app $HEROKU_FASTAPI_APP



## DEPLOY THE UI
pages:  # THIS STEP MUST BE NAME PAGES
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  dependencies:
    - build-front-end-job
  needs:
    - build-front-end-job
  script:
     # THE FIRST PART OF THIS COMMAND MUST BE THE DIRECTORY
     # THAT YOU cd INTO TO BUILD IT PLUS THE build/ AT THE
     # END
    - mv ghi/build/ public
  artifacts:
    paths:
      - public